//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//123
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------

namespace KT100720_59132942.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiSan
    {
        public int MaTS { get; set; }
        public string TenTS { get; set; }
        public string DVT { get; set; }
        public bool XuatXu { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Yêu cầu nhập đơn giá")]
        [Range(1000000, 10000000, ErrorMessage = "Đơn giá phải nhập 1000000 and 10000000")]
        public int DonGia { get; set; }
        public string AnhMH { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaLTS { get; set; }
    
        public virtual LoaiT LoaiT { get; set; }
    }
}
